name: Sharingan
on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

env:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: test
  MYSQL_PORT: 3306
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  ADMIN_PASSWORD: admin_password
  CONVERTKIT_API_KEY: api_key
  CONVERTKIT_FORM_ID: form_id

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install projects dependencies
        uses: bahmutov/npm-install@v1

      - name: Lint the projects
        run: yarn lint

      - name: Build the projects
        run: yarn build

      - name: Start MySQL server
        run: sudo systemctl start mysql.service

      - name: Run tests
        run: yarn test
