name: Sharingan Deploy
on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/ci-api.yml'

jobs:
  package:
    if: ${{ github.ref == 'refs/heads/main' }}
    defaults:
      run:
        working-directory: .
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Dashboard to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.api
          push: true
          tags: tericcabrel/sharingan-core:latest

  deploy:
    if: ${{ github.ref == 'refs/heads/main' && github.event.inputs.should_deploy == 'yes' }}
    defaults:
      run:
        working-directory: .
    runs-on: ubuntu-latest
    needs:
      - package
    steps:
      - uses: actions/checkout@v2
      - name: Add Server key
        run: |
          touch key.txt && echo "${{ secrets.SERVER_KEY }}" > key.txt
          chmod 600 key.txt
      - name: Deploy the application
        run: |
          export SUSER=${{ secrets.SERVER_USER }}
          export SNAME=${{ secrets.SERVER_NAME }}
          export SPORT=${{ secrets.SERVER_PORT }}
          ./deploy.sh
