name: Sharingan Deploy Core
on:
  workflow_dispatch:
    inputs:
      commit-sha:
        description: "SHA of the latest commit in the pull request"
        required: true

env:
  IMAGE_TAG: tericcabrel/sharingan-core:${{ github.event.inputs.commit-sha }}

jobs:
  package:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v2

      - name: Copy the core Dockerfile in the root repository
        run: cp apps/core/Dockerfile .

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: $IMAGE_TAG

  deploy:
    defaults:
      run:
        working-directory: apps/core
    runs-on: ubuntu-latest
    environment: Production
    needs:
      - package
    steps:
      - uses: actions/checkout@v2
      - name: Add Server key
        run: |
          touch key.txt && echo "${{ secrets.SERVER_KEY }}" > key.txt
          chmod 600 key.txt
      - name: Deploy the application
        run: |
          export SUSER=${{ secrets.SERVER_USER }}
          export SNAME=${{ secrets.SERVER_NAME }}
          export SPORT=${{ secrets.SERVER_PORT }}
          export IMAGE_TAG=$IMAGE_TAG
          ./deploy.sh
